name: Build

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          dependency-graph: generate-and-submit

      - name: Build
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: JMWaypointsToXaero
          path: build/libs/JMWaypointsToXaero-*.jar
          if-no-files-found: error
